Kp: 0.35
Kd: 0.12
L: 1.2
L_speed: 0.8
speed_min: 1.0
speed_max: 5.0
speed_min_linear: 0.8 #0.8
speed_max_linear: 4.5
# csv_file_path: '/home/angli/sim_ws/src/pure_pursuit/waypoints/race2_1.csv'
# csv_file_path: '/home/nvidia/f1tenth_ws/src/pure_pursuit/waypoints/race2_1.csv'
# csv_file_path: '/home/angli/sim_ws/src/pure_pursuit/waypoints/race2_2.csv'
# csv_file_path: '/home/nvidia/f1tenth_ws/src/pure_pursuit/waypoints/race2_2.csv'
# csv_file_path: '/home/angli/sim_ws/src/pure_pursuit/waypoints/race2_3.csv'
# csv_file_path: '/home/nvidia/f1tenth_ws/src/pure_pursuit/waypoints/race2_3.csv'
# csv_file_path: '/home/angli/sim_ws/src/pure_pursuit/waypoints/race2_0401.csv'
csv_file_path: '/home/nvidia/f1tenth_ws/src/pure_pursuit/waypoints/race2_0401_4.csv'
# csv_file_path: '/home/nvidia/f1tenth_ws/src/pure_pursuit/waypoints/race2_0401_4_realrace.csv'
# csv_file_path: '/home/nvidia/f1tenth_ws/src/pure_pursuit/waypoints/race2_0401_5_realrace.csv'
